diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager
pull.rebase=false
user.name=Mohamed Daher
user.email=madaher@alumni.ie.edu
core.editor=vi
gui.recentrepo=C:/Users/Zaher/Desktop/Coursera2/git-test
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.heroku.url=https://git.heroku.com/mal3ab.git
remote.heroku.fetch=+refs/heads/*:refs/remotes/heroku/*
remote.origin.url=git@github.com:madaher-dev/mal3ab.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
